### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by Geotomo** [Junxiao-Zhao/Curve_fitting_PINN#1]
Hi Dr Zhao
I am running your this script (the name is curve.fitting.py), and the screen shows the following messages:

Traceback (most recent call last):
  File "curve.fitting.py", line 191, in <module>
    model.train(5000)
  File "curve.fitting.py", line 150, in train
    self.Adam_optimizer(nIter)
  File "curve.fitting.py", line 135, in Adam_optimizer
    self.optimizer_Adam.minimize(self.loss_NN, varlist, tape=tape)
TypeError: minimize() got an unexpected keyword argument 'tape'

Do you have any idea of how to fix it?

Best Regards

**Comment by Junxiao-Zhao** [comment]
Hi Weiguang,

I think this error may occur due to the different TensorFlow versions we use. Unfortunately, I have lost the version information. But I have rewritten [PINN using PyTorch](https://github.com/Junxiao-Zhao/Physical-Informed_Neural_Network). Please check if you'd like to.

Best regards
